set_property IOSTANDARD LVCMOS18 [get_ports a]
set_property IOSTANDARD LVCMOS18 [get_ports b]
set_property IOSTANDARD LVCMOS18 [get_ports c]
set_property IOSTANDARD LVCMOS18 [get_ports f]
set_property PACKAGE_PIN D7 [get_ports f]
set_property PACKAGE_PIN A7 [get_ports a]
set_property PACKAGE_PIN A8 [get_ports b]
set_property PACKAGE_PIN A9 [get_ports c]
